### ISSUE TITLE
reproduce the released checkpoints

### ISSUE THREAD

**Issue by andyaloha** [cremebrule/digital-cousins#13]
Could you please provide the process for reproducing the training of the 'cousin_ckpt.pth' and 'twin_ckpt.pth' files? Thank you.

**Comment by RogerDAI1217** [comment]
Hi @andyaloha, to save your time, here is the models we used for the twin v.s. cousins experiments on door opening task.

### Use DINO to select digital cousins:

- Twin: kdbgpm
- 2 Cousins: tolupn, hrdeys
- 4 Cousins: tolupn, hrdeys, rvunhj, vceupd
- 8 Cousins: tolupn, hrdeys, rvunhj, vceupd, xpdbgf, pzjecb, vespxk, glefdh
- Test Assets: kdbgpm, dajebq (Hold-out 2nd digital cousin), nrlayx (Hold-out 6th digital cousin), plccav

### Use DINO + GPT to select digital cousins:

- Twin: kdbgpm
- 2 Cousins: hrdeys, rvunhj
- 4 Cousins: hrdeys, rvunhj, nrlayx, nyfebf
- 8 Cousins: hrdeys, rvunhj, nrlayx, nyfebf, glefdh, smujam, vceupd, pzjecb
- Test Assets: kdbgpm, dajebq (Hold-out 2nd digital cousin), xpdbgf (Hold-out 6th digital cousin), plccav
- Due to LLM prompting, the digital cousin selection can contain some randomness

We trained BC-RNN with different hyperparameters. The average success rates  are reported in **Table 3**, **Table 4**, **Table 5**, **Figure 7**, **Figure 13**, and **Figure 14** in **Appendix**.

**Comment by andyaloha** [comment]
@cremebrule @RogerDAI1217 Thanks. I have trained a valid policy according to your instruction with twin of kdbgpm and 8 cousins in the config of twin_ckpt.pth. While in evaluation, it seems that the target object must be one of those in the loaded scene? This scene is specified in the demos collection step by scene_path, which is saved into the .hdf5 file and loaded as the test scene in the evaluation step. How can I change the target object to others not in the loaded scene (such as different hold-out cousins)?

**Comment by cremebrule** [comment]
Hi @andyaloha ,

Great question. I believe we already have this implemented -- you can simply set the `eval_category_model_link_name` in the evaluation script [`examples/4_evaluate_policy.py`](https://github.com/cremebrule/digital-cousins/blob/main/examples/4_evaluate_policy.py). Can you try that?

**Comment by andyaloha** [comment]
@cremebrule I have tried it. No matter how I change the target object by eval_category_model_link_name, the final target object is always the same kdbgpm. It seems that the target object is fixed by the scene_path as in the demos collection step, which is saved into the .hdf5 file and loaded as the test scene in the evaluation step.

**Comment by cremebrule** [comment]
Hi @andyaloha ,

Hmmmm that's strange. I just tested our twin checkpoint now with `--eval_category_model_link_name "bottom_cabinet,dajebq,link_3"`, and it seems to work fine.

Do you have a repro (checkpoint + command you executed) that we can try?

**Comment by RogerDAI1217** [comment]
Hi @andyaloha, we've looked into your issue. Could you please pull the latest changes to see if it works for you now?

The bug is because the index of evaluation asset is ``ckpt_dict["env_metadata"]['env_kwargs']['og_config']['wrapper']['eval_idx']``. For checkpoints we released, we set the ``eval_idx`` to -1, i.e., the last asset will be the evaluation asset. If you set eval_idx to other values (e.g., 0) in ``3_train_policy.py``, the original script will put the evaluation asset to index -1 without changing eval_idx, which cause the bug. **The newest code should be able to fix the problem**.

All test-time configs can be modified in similar way. In the newest code, we also allow users to change the aggressiveness of randomization during evaluation. Please check [here](https://github.com/cremebrule/digital-cousins/blob/49400bb4aca50eea97490c9c9f1b4431e50792dd/examples/4_evaluate_policy.py#L14) if you are interested.

**Comment by cremebrule** [comment]
Closing for now. Please reopen if issues persist!
