### ISSUE TITLE
some error when test_model.py

### ISSUE THREAD

**Issue by codetea-fly** [cremebrule/digital-cousins#9]
Hi~
Excellent work! But i encounted a problem when running test_model.py. it shows that" libhdx.so: cannot open shared object file: No such file or directory " when running the command "og.launch", any solution ? thx~
![image](https://github.com/user-attachments/assets/680893d2-f3fc-43c8-916c-dc0f5ca04e0c)

**Comment by Yang-SyZng** [comment]
It looks like the OGdataset is not being downloaded, have you run this command? This commad will download and install three dataset
> python -m omnigibson.utils.asset_utils --download_assets --download_og_dataset --accept_license

**Comment by codetea-fly** [comment]
Yes, i have downloaded the dataset, it seems i should install vulkan on ubuntu. after i installed vulkan, the error turns to be a warning when running command "og.launch".
![image](https://github.com/user-attachments/assets/3e2db93d-ae10-4d66-bdf8-6ce633053a77)
![image](https://github.com/user-attachments/assets/7e18ba51-c1c3-415e-8eb0-fd229186656f)
By the way, i use WSL2 to run omnigibson, is it able to run in WSL2 ?

**Comment by Yang-SyZng** [comment]
Maybe OmniGibson does not support the WSL platform. This is just my guess, as I have never used WSL. I have run it successfully on Ubuntu. The role of OmniGibson is to render and display the matched 3D digital cousins results, which usually requires GUI support. WSL is just a command line tool and does not have such an environment. 
However, I can give some maybe useful suggestions. This project has three steps in total. You can try to run "Real World Extraction" and "Digital Cousin Matching" in WSL, because these two steps do not rely on OmniGibson. "Simulated Scene Generation" can be run in the Windows environment. Or you can install a new Ubuntu system. Although it is a little troublesome, it is really convenient! lol!

**Comment by codetea-fly** [comment]
Thanks a lot! actually i have successfully finish the first two step. i have commit a issue in OmniGibson's github forum too. And i searched a lot on nvidia forum. it seems that isaacsim does not support WSL in 2021. 
I will try to run the step3 in windows env~ thx.

**Comment by cremebrule** [comment]
Hi @codetea-fly ,

Yes, unfortunately, as far as I know WSL cannot support IsaacSim because Linux requires low-level access to the NVIDIA GPU, which is not allowed.

OmniGibson itself can run directly on Windows -- however, we haven't tested our digital_cousins repo on Windows (only Linux).

**Comment by cremebrule** [comment]
Closing this issue for now -- feel free to reopen if any issues persist!
